# Generated by Django 2.2.5 on 2019-10-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=30)),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=200)),
                ('attachment', models.FileField(upload_to='')),
                ('subject', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailReceiverTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers', models.EmailField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailSendgrid.EmailModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmailReceiverCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc', models.EmailField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailSendgrid.EmailModel')),
            ],
        ),
        migrations.CreateModel(
            name='EmailReceiverBCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcc', models.EmailField(max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailSendgrid.EmailModel')),
            ],
        ),
    ]
